name: InfoBlock
main: dvntx.infoblock.InfoBlocks
version: 1.0.0
api: ["3.0.0"]
description: Muestra el historial (colocado / roto / abierto) de bloques y cofres.
author: DVNTX1

permissions:
  infoblock.use:
    default: op
